# Example Workflow for NRC-Deployment
name: Run Deployment

on:
  push:
    branches:
    - main
    - development
    - production
  
  pull_request: # Trigger Workflow on pull-request of a listed branch
    branches:
    - main
    - development
    - production

  workflow_dispatch: # Manual Run

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deployment"
  cancel-in-progress: false

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        run: echo Test
          
# Reihenfolge ist btw. nicht random, ist am sinnvollsten und basiert aufeinander. :nerd:
# als erstes wird Dev deployed wenn Build erfolgreich war, dann Main wenn Dev erfolgreich war und als letztes Prod (weiß nd, ist der überhaupt nötig?)
    DeployDev:
      name: Deploy to Development-Server
      if: github.event_name == 'pull-request'
      needs: [Build]
      runs-on: ubuntu-latest
      environment:
        name: Development
        url: 'https://dev.norisk.gg/' # Beispielhafte URL
      steps:
        - name: Deploy
          run: echo Deploying Development to Server
          
        DeployMain:
      name: Deploy to Main-Server
      if: github.event.ref == 'refs/heads/main' # only if main is selected
      needs: [DeployDev]
      runs-on: ubuntu-latest
      environment:
        name: Main
        url: 'https://main.norisk.gg/'
      steps:
        - name: Deploy
          run: echo Deploying Main to Server

    DeployProd:
      name: Deploy to Production-Server
      if: github.event_name == 'pull-request'
      needs: [DeployMain]
      runs-on: ubuntu-latest
      environment:
        name: Production
        url: prod.nrc.server
      steps:
        - name: Deploy
          run: echo Deploying Production to Server
